### ISSUE TITLE
Party Bug

### ISSUE THREAD

**Issue by Albert481** [pronze/SBAHypixelify#11]
1. if u /p invite someone and they join ur party but they leave the game, the /p list still has their name on it
2.  join into the game
3. the game will think u are with more then one person but ur not
4. the game will begin

**Comment by pronze** [comment]
That's because there's a 60 second timeout for the person to get auto removed from the party. And the game doesn't begin if the player itself doesn't join it, as the plugin does not mock player entities or "force start" the game anyhow.
