### ISSUE TITLE
Bug: Players cannot execute `bwaddon gamesinv`

### ISSUE THREAD

**Issue by garagepoort** [pronze/SBAHypixelify#13]
Players cannot execute the command `bwaddon gamesinv`. Only if they are given admin privileges this works.
Can be fixed by setting the permission to null in the super constructor call in the Class `BWACommand`

```
public BWACommand() {
        super(null, true, "bwaddon");
    }
```

Permissions will be completely handled inside the `onPreExecute` method

```
    @Override
    public boolean onPreExecute(CommandSender sender, String[] args) {
        if (sender instanceof Player) {
            if (!sender.hasPermission("misat11.bw.admin") &&
                    !args[0].equalsIgnoreCase("gamesinv")) {
                sender.sendMessage("§cYou Don't have permissions to do this command");
                return false;
            }
        }
        return true;
    }
```

**Comment by garagepoort** [comment]
https://github.com/pronze/SBAHypixelify/pull/14

**Comment by pronze** [comment]
Actually the permissions are handled inside the AbstractCommand class. Check that out.

All we need to do here is to remove the code onPreExecute method and set null to the constructor(as you said) will be doing that soon

**Comment by pronze** [comment]
Thank you for notifying me, somewhere recently I used abstraction as a method of simplifying the command classes, and I had forgotten about that :)
