### ISSUE TITLE
Player tag prefixing is not working

### ISSUE THREAD

**Issue by zannapzg** [pronze/SBAHypixelify#15]
Hi, I am using your addon for ScreamingBedwars
I'm having a problem with the players prefix ..
They are white (like not formatted?), they do not have the color / team name

**Comment by zannapzg** [comment]
(The nametag)

**Comment by pronze** [comment]
Could you send a screenshot?, and do you use any tab plugins?

**Comment by zannapzg** [comment]
![image](https://user-images.githubusercontent.com/61860483/100486967-be778200-3106-11eb-9c5f-8fc67a5a3d8b.png)


![image](https://user-images.githubusercontent.com/61860483/100486982-cafbda80-3106-11eb-9009-c9fc167697fc.png)

**Comment by zannapzg** [comment]
No, I'm not using any plugin that edit the nametag in tablist

**Comment by pronze** [comment]
use the latest version 1.3.8 from the spigot site. Fixed it.
