### ISSUE TITLE
Can u make an this SBAHypixelify for Pokkit?

### ISSUE THREAD

**Issue by Hoangviphb999** [pronze/SBAHypixelify#16]
Im using Pokkit which is translate a Spigot/Bukkit plugins into Nukkit plugins but it have some error like your villager won't work and the PlayerJoinEvent

**Comment by Hoangviphb999** [comment]
![Uploading Screenshot_20201128-135332_Chrome.jpg…]()

**Comment by pronze** [comment]
This plugin does not provide support for Pokkit.
