### ISSUE TITLE
starting armour and permanent armour vanishing on death

### ISSUE THREAD

**Issue by ABarbecue** [pronze/SBAHypixelify#18]
After starting a round and dying I keep losing the starting armour or any permanent armour i had on

**Comment by pronze** [comment]
Paste your latest.log file (Found inside of the logs folder of your server) at https://www.pastebin.com and send me a link to it.

**Comment by ABarbecue** [comment]
[2020-11-29-6.log](https://github.com/pronze/SBAHypixelify/files/5612485/2020-11-29-6.log)

**Comment by ABarbecue** [comment]
https://pastebin.com/aX2VijNQ

**Comment by pronze** [comment]
Minecraft server version 1.8.8 isn't supported by screaming bedwars or sbahypixelify, upgrade your server to atleast 1.9.4
