### ISSUE TITLE
Other 2 bugs!

### ISSUE THREAD

**Issue by zannapzg** [pronze/SBAHypixelify#19]
Hi, I was testing bedwars and I discovered 3 bugs..
The first one is about the shop: I can't downgrade my tools (pickaxe, sword, axe) without losing them
Usually I should lose them only after an upgrade...
[>Click here for the video!<
](https://tlgur.com/d/gm5pJk2g)

Others 2 bugs are in this video:
If I die (only in 1.8) I will respawn gitched.. look at the video that I've attached.
The last problem is that if I die and the last damage cause is tnt I will respawn under the world.
[>Click here for the video!<
](https://tlgur.com/d/8KoPQOQ8)

**Comment by pronze** [comment]
Send your latest.log file via https://www.pastebin.com

**Comment by zannapzg** [comment]
> Send your latest.log file via https://www.pastebin.com

There is no error in console
