### ISSUE TITLE
Bug with scoreboard

### ISSUE THREAD

**Issue by squeaky2137** [pronze/SBAHypixelify#20]
Console keeps getting spammed with this when in a match
[Wed, 2. Dec 2020 01:33:41 GMT INFO] Tried to update score without the existence of its requested objective 'bwa-tag'
[Wed, 2. Dec 2020 01:33:41 GMT INFO] Tried to update score without the existence of its requested objective 'bwa-tab'
[Wed, 2. Dec 2020 01:33:41 GMT INFO] Tried to update score without the existence of its requested objective 'bwa-tab'
[Wed, 2. Dec 2020 01:33:41 GMT INFO] Tried to update score without the existence of its requested objective 'bwa-tag'
[Wed, 2. Dec 2020 01:33:42 GMT INFO] Tried to update score without the existence of its requested objective 'bwa-tag'
[Wed, 2. Dec 2020 01:33:42 GMT INFO] Tried to update score without the existence of its requested objective 'bwa-tab'
Etc...
Also this probably has to do with it but ingame the scoreboard whenever it tries to update it for diamond upgrade time it just spams scoreboard with a new diamond [time] so it ends up filling scoreboard [probs bug on my end]

**Comment by pronze** [comment]
Could you send your entire latest.log file?

**Comment by squeaky2137** [comment]
Oop just read it for the tried to update and that was another plugin issue sorry but while I am here do you know how to make it so the player inventory clears after a game since I am using multiverse so they keep their inv the next game.

**Comment by squeaky2137** [comment]
Nvm apparently wit this plugin 
![1C8A5825-E8B1-46FC-B18F-F9B6D562A826](https://user-images.githubusercontent.com/73867896/100940458-99e02900-34bd-11eb-8841-4b33d5659f5b.png)
![C9995B4D-52AD-4785-B443-62F8ADECE639](https://user-images.githubusercontent.com/73867896/100940470-9ea4dd00-34bd-11eb-97ca-9fd47053640d.png)

**Comment by pronze** [comment]
Please send the file using https://www.pastebin.com

**Comment by pronze** [comment]
This plugin don't provide support for Geyser
