### ISSUE TITLE
 Bugs | Spawners

### ISSUE THREAD

**Issue by MrGoodPlugins** [pronze/SBAHypixelify#24]
Bugs | 1. i respawn and not give me the items | Spawners | 2. That one spawner works the rest do not work and it shows instead of diamond/emerald - stand armor

**Comment by pronze** [comment]
Could you send your latest.log file? and what version of sbahypixelify are you using?

**Comment by MrGoodPlugins** [comment]
1.4.0 and which file of the plugin? bwconfig or config?

**Comment by MrGoodPlugins** [comment]
I am now using version 1.4.2

**Comment by MrGoodPlugins** [comment]
1.4.2 this not config

**Comment by pronze** [comment]
Not any file of the plugin, you'll need to send server logs for me to be able to diagnose an issue. It's the latest.log file inside your logs folder, Make sure to reproduce the error then send the logs

**Comment by MrGoodPlugins** [comment]
this config 1.4.2 is completely empty

**Comment by pronze** [comment]
Again I need your server logs to verify the problem, and it's most likely you haven't installed Java 11 yet

**Comment by pronze** [comment]
Closing issue as you've confirmed you're using java 8. Next time do read the spigot site properly before posting bug reports as it will help save some time
