### ISSUE TITLE
Message to owner the plugin

### ISSUE THREAD

**Issue by MrGoodPlugins** [pronze/SBAHypixelify#25]
Plugin owner will address issues please version now it does not work at all

**Comment by pronze** [comment]
You'll need to switch to Java 11 to use this plugin, if you're already using Java 11 send your latest logs.

**Comment by MrGoodPlugins** [comment]
You dropped a bag on me

**Comment by MrGoodPlugins** [comment]
and why not java 8?

**Comment by pronze** [comment]
Java 8 is outdated and out of support. It's time to move on anyways.

Closing issue
