### ISSUE TITLE
Scoreboard bug

### ISSUE THREAD

**Issue by squeaky2137** [pronze/SBAHypixelify#26]
Sometimes the scoreboard when updating puts teams / beds below the date and website for example this image is what it does
![D8D204C5-9A8E-4AB1-BAAA-12A26EA98F92](https://user-images.githubusercontent.com/73867896/102703875-5cf49000-423a-11eb-89a5-7d75801282f9.png)
It shows that and only worked 1 time correctly
also is there a way to make main lobby scoreboard only show up for people in that world and make the chats only work in that world.

**Comment by pronze** [comment]
We don't provide support for bedrock edition, you should contact the owner of the proxy/bridge provider about this issue

**Comment by squeaky2137** [comment]
Yes I did I notice this after testing with java as I thought java had Same issue :/ Lol sorry
