### ISSUE TITLE
Small tip / request

### ISSUE THREAD

**Issue by zannapzg** [pronze/SBAHypixelify#27]
Can you add translatable tiers?
Tiers like diamond and emerald
Not only the name of the tiers but the full message
I want to translate "Diamond I in 10:00" in "Diamante I tra 10:00"
Because not in all languages ​​they are written that way

Sorry for by bad english

**Comment by pronze** [comment]
Feature added in the latest snapshot #58

https://ci.screamingsandals.org/job/SBAHypixelify/58/

Download the "SBAHypixelify-1.4.4-SNAPSHOT-all.jar" 

you should customize the text in floating-generator config section in bwaconfig.yml
