### ISSUE TITLE
Error/warning with scoreboard

### ISSUE THREAD

**Issue by zannapzg** [pronze/SBAHypixelify#29]
![image](https://user-images.githubusercontent.com/61860483/102793434-2dfd2c00-43aa-11eb-9456-b955ba8c0bdc.png)
Error displayed when a player slog
Server version: 1.12.2
Paper version git-Paper-1618
Plugins:
![image](https://user-images.githubusercontent.com/61860483/102793509-4ec58180-43aa-11eb-9dc3-4fb9965060fe.png)

**Comment by pronze** [comment]
Fixed in snapshot #58 https://ci.screamingsandals.org/job/SBAHypixelify/58/

download the "SBAHypixelify-1.4.4-SNAPSHOT-all.jar" and test it out, if it does not work feel free to reopen this issue
