### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by MrSandwich14** [pronze/SBAHypixelify#3]
So i did as it told me to do and for some reason the shop isnt working the villagers are just farmers that sell wheat and stuff like that anyone know how to fix? my discord is  _Sandwich_ⱽᵉʳⁱᶠⁱᵉᵈ ᵒᴺ ᴼᶰᴸʸᶠᵃᴺˢ#8574

**Comment by pronze** [comment]
If you don't have citizens enabled then in your bwaconfig.yml disable citizens-shop, if not then send your latest logs.

**Comment by pronze** [comment]
Closing issue because of no response, feel free to reopen it if you still are facing the issue
