### ISSUE TITLE
Request / Issue

### ISSUE THREAD

**Issue by LordVZlomka** [pronze/SBAHypixelify#30]
1) The message "The game will start in X seconds" doesn't start properly It starts at the last 5 seconds, also at the beginning it posts a message "The game will start in 1 second", then it waits until 5 seconds left and start sending the messages.
2) Please fix the issue when the plugin notifies you to update, ignoring the fact that you have the latest version.

![Screenshot_7](https://user-images.githubusercontent.com/71541816/102794315-35581180-4379-11eb-9d66-cc751bd7d59f.png)

**Comment by pronze** [comment]
Snapshot #58 fixes this issue, if not feel free to reopen this issue.

https://ci.screamingsandals.org/job/SBAHypixelify/58/
