### ISSUE TITLE
New experimental reset-item-meta-on-purchase problem e.e

### ISSUE THREAD

**Issue by zannapzg** [pronze/SBAHypixelify#31]
Hi, thank you for adding the "reset-item-meta-on-purchase" function

Small problem, in the shop there is an item (the knockback stick) and when I buy it loses the enchant
![image](https://user-images.githubusercontent.com/61860483/102949789-68a9b600-44c9-11eb-8192-e36de67a0dbc.png)
![image](https://user-images.githubusercontent.com/61860483/102949805-72331e00-44c9-11eb-9809-c46559591249.png)

**Comment by pronze** [comment]
Fixed on the latest snapshot
