### ISSUE TITLE
Problem with generators

### ISSUE THREAD

**Issue by zannapzg** [pronze/SBAHypixelify#32]
![2020-12-23_02 50 30](https://user-images.githubusercontent.com/61860483/102950068-0d2bf800-44ca-11eb-86a5-97e47eb57486.png)

Hi, I have a problem with generators
The level is always 0
As you can see in scoreboard I reached Emerald III (3) and the generator still on 0
Same problem with emerald generators

**Comment by zannapzg** [comment]
![image](https://user-images.githubusercontent.com/61860483/102950105-2634a900-44ca-11eb-974b-ad2ff1855bb2.png)
Here the config

**Comment by pronze** [comment]
Fixed on the latest snapshot
