### ISSUE TITLE
Killing a player does not increase current kill count in match

### ISSUE THREAD

**Issue by Buyingbf** [pronze/SBAHypixelify#35]
When I kill an enemy player in a Bedwars match, my current kill count does not go up. In fact, the person I killed gets a kill added to their killcount.

![1](https://user-images.githubusercontent.com/45669945/103051907-b1568300-454c-11eb-8558-ee8b355ad299.png)
![2](https://user-images.githubusercontent.com/45669945/103051922-be737200-454c-11eb-813f-4acc3136f38e.png)

Overall player stats are counted correctly, however.

**Comment by pronze** [comment]
Fixed in the latest snapshot: https://ci.screamingsandals.org/job/SBAHypixelify/74/

if your server host does not allow uploading your own jars, you'll have to wait for the update to be uploaded on the spigot site.
