### ISSUE TITLE
Iron forge and heal pool

### ISSUE THREAD

**Issue by SamSamsung** [pronze/SBAHypixelify#36]
Describe the bug
The iron upgarde doesn't work, even if i put ALL of my iron in it, it won't work and same for heal pool.

Server and plugin version
Spigot version: 1.16.4
SBA Hypixel BedWars version: (4.2, i think)

Installed plugins on server (can be obtained by /pl)
- Multicore
- Bedwars
- Citizen
- Via backwards
- Via version
- hologramm
- Wolrd edit
Console log
Configuration (of config.yml and shop.yml)
If there are problem with only one game, paste here config of this game

**Comment by pronze** [comment]
send your console logs here.
