### ISSUE TITLE
Blindless trap and heal pool not working

### ISSUE THREAD

**Issue by Buyingbf** [pronze/SBAHypixelify#38]
Currently running on 1.4.4 build #79. I upgraded from release 1.4.3, and on that version the blindless trap worked. On this version of the build, when a player buys the blindless trap, they are given string instead of having a trap placed on the island.

Additionally, heal pool is not working either. Players are only given a beacon that does not regen health when placed. 

Side note: Any way to set a cap on iron generation upgrades at a team's base? Players can quickly upgrade the spawner to generate a stack of iron every second. Also if gold generation can be upgraded as well?

**Comment by pronze** [comment]
Seems like listener isn't working properly, I will look into this thanks for the information.

Also I will work on the generator upgrades cap later, it surely is on my Todo list.

**Comment by pronze** [comment]
Fixed in the latest snapshot, try it out.
