### ISSUE TITLE
Right GUI Bug

### ISSUE THREAD

**Issue by Doudou8** [pronze/SBAHypixelify#4]
<img width="2048" alt="Screen Shot 2020-08-07 at 1 11 23 AM" src="https://user-images.githubusercontent.com/49688773/89611334-ec307680-d84a-11ea-88be-c21bb34720a4.png">

When the starts or when you are in the lobby, the GUI on the right side is flashing between the default one by ScreamingBedwars and the one added by this plugin. I have the latest versions of both ScreamingBedwars and SBAHypixelify. I'm using Minecraft 1.16.1.

**Comment by pronze** [comment]
Disable lobby-scoreboard and game-scoreboard from the BedWars config.
