### ISSUE TITLE
config question

### ISSUE THREAD

**Issue by zannapzg** [pronze/SBAHypixelify#41]
Which file should I use for the shop and upgrades?
Until now I was using legacy-shop because shop.yml didn't work
And now shop.yml works

I'm confused

**Comment by MrGoodPlugins** [comment]
There was probably a problem I'm sure they'd sorted out if it works for you now

**Comment by linusstretchtips** [comment]
Hello!
Greg here over from ScreamingSandals  👍

the legacy shop is for servers <1.13 while the normal shop.yml is for 1.13+

Have a great day 😊

**Comment by zannapzg** [comment]
> Hello!
> Greg here over from ScreamingSandals 👍
> 
> the legacy shop is for servers <1.13 while the normal shop.yml is for 1.13+
> 
> Have a great day 😊

Okey thanks
