### ISSUE TITLE
upgrade shop

### ISSUE THREAD

**Issue by MrGoodPlugins** [pronze/SBAHypixelify#42]
Need to do 3 columns for upgrades instead of 8
its not so pretty without offending yes?

**Comment by RyanGamingXbox** [comment]
Please do **not make** duplicate issues. But I'm pretty sure you can edit the `upgradeshop.yml` file for that.

**Comment by pronze** [comment]
You can edit them in the bedwars config.yml shop section, if you want a separate config for it reopen this issue.
