### ISSUE TITLE
Hologram generator question/bug

### ISSUE THREAD

**Issue by zannapzg** [pronze/SBAHypixelify#44]
![2021-01-04_19 10 54](https://user-images.githubusercontent.com/61860483/103565431-9f67cf00-4ec0-11eb-9b90-115f819da3f6.png)

Hi, I'm trying to lift the generator block a little higher, under the hologram

But I can not..
I changed the height of the hologram from 2.0 to 3.0 and it worked, the block doesn't (I tried switching from 0.25 to 1.5)

Config:
![image](https://user-images.githubusercontent.com/61860483/103565652-f7063a80-4ec0-11eb-8c36-89753d9b96ac.png)

**Comment by pronze** [comment]
Fixed in the latest snapshot #83
https://ci.screamingsandals.org/job/SBAHypixelify/83/
