### ISSUE TITLE
shop/upgrade shop does not work

### ISSUE THREAD

**Issue by N1kkogg** [pronze/SBAHypixelify#46]
i cant see the shop in game idk why i did this command /bw admin boletum store add Store shop.yml false
my server version is 1.9.4 and i run paper spigot

**Comment by N1kkogg** [comment]
i have java 11 btw

**Comment by N1kkogg** [comment]
**Resolved** ALWAYS CHECK IF YOU ARE PROTECTING YOUR WORLD WITH mob-spawning DENY

**Comment by N1kkogg** [comment]
i love this plugin

**Comment by pronze** [comment]
Thank you :)
