### ISSUE TITLE
Default config does not have colored game inventories and lore.

### ISSUE THREAD

**Issue by RyanGamingXbox** [pronze/SBAHypixelify#48]
The default config uses **&** instead of **§** and when opening `bwa gamesinv <mode>` will not apply color codes as intended.
The latest snapshot of **SBAHypixelify** also does not apply the lore as it's meant to be.

[Color Code Not Applied](https://user-images.githubusercontent.com/30727670/104428120-0a02c400-55bf-11eb-9819-c543a6e17bc6.png)
[Lore Not Shown](https://i.imgur.com/2xl7j6a.png)

**Comment by pronze** [comment]
Use the latest snapshot
