### ISSUE TITLE
So 2 problems

### ISSUE THREAD

**Issue by ToxicKid182** [pronze/SBAHypixelify#5]
1 How do you delete the villagers
2 The TeamUpgrade Is not working

**Comment by pronze** [comment]
Please provide your latest logs for me to be able to diagnose your problem. Also to remove a store do /bw admin <mapname> store remove. On the same place you spawned the store before

**Comment by pronze** [comment]
Closing issue because of no response, feel free to reopen it if you still are facing the issue
