### ISSUE TITLE
Scoreboard bug

### ISSUE THREAD

**Issue by zannapzg** [pronze/SBAHypixelify#54]
![image](https://user-images.githubusercontent.com/61860483/104658060-5aaf1580-56c2-11eb-918f-41d471d9a71e.png)

Hi, the scoreboard returns null
Apparently no one has a scoreboard with buggy lines ... or incomplete

**Comment by RyanGamingXbox** [comment]
I also found this bug in the latest build of **SBAHypixelify**. `(Build 101)`

**Comment by RyanGamingXbox** [comment]
This is fixed in **Build 102**.
