### ISSUE TITLE
Show player health

### ISSUE THREAD

**Issue by dragonwocky** [pronze/SBAHypixelify#6]
Hey, it'd be great if player health could be shown under their name / in the tab menu.

I attempted to build my own plugin following https://www.spigotmc.org/threads/health-under-player-name.402910/ (adding on the onmove event if in an enabled world), and it works during normal gameplay, but it conflicts with the bedwars scoreboard and brings in some weird behaviour (flickering between the health display, the pre-game scoreboard and the during-game scoreboard). Then after the game it shows everyone's health as 0 and the pre-game scoreboard is still visible.

![2020-08-26_17 02 03](https://user-images.githubusercontent.com/16874139/91271973-5d19dd00-e7be-11ea-9b14-11153b61dc77.png)

I don't have a lot of experience with Java/Bukkit, so though I theoretically understand the problem I'm a bit lost on how to fix it. Is this something you could help with, or add into this plugin? Or would it be better for me to open this issue in the core ScreamingBedwars repo? 

(I also tried just attaching the health objective to whatever the player's current scoreboard was, but then it was always showing as 0.)

**Comment by pronze** [comment]
Hey, this feature is already in the addon. Just install ProtocolLib and use the latest version of the addon :)

**Comment by dragonwocky** [comment]
Sweet, thankyou, I must've missed that! Is it written anywhere in the wiki/readme?

**Comment by pronze** [comment]
Oh now that I look at it, I haven't documented that feature anywhere haha. I will do now, Thanks for reminding me :)
