### ISSUE TITLE
Major Bug with Floating Generators

### ISSUE THREAD

**Issue by Ansif06** [pronze/SBAHypixelify#62]
The floating generatores work as usual they turn and stuff
But there is always a stagnant floating generator in game and not in game 
so when the floating genratoris rotating it looks as if it is glitching
And when i am not in game there is a floating generator in its place not rotating
Pls help

**Comment by pronze** [comment]
Can you try using the latest snapshot and see if it fixes it?
link: https://ci.screamingsandals.org/job/SBAHypixelify/

**Comment by Ansif06** [comment]
Thanks for the reply but i have already tried the snapshot and it doesnt work
The snapshot causes errors 
In the console it says (Is it up to date?) and disables plugins - I also had screaming bedwars 0.3.0
Anyways i fixed it
As i had made a backup before adding sbahypixelify 
I deleted my bedwars map and re added it this time it was perfect 
Thanks for the help by the way

**Comment by pronze** [comment]
Great to know it's fixed!, thanks for responding :)
