### ISSUE TITLE
Scoreboard Error Spam when someone isn't online.

### ISSUE THREAD

**Issue by RyanGamingXbox** [pronze/SBAHypixelify#63]
I haven't been able to reproduce it sadly. But this error happened when no one was online.
This error doesn't really effect anything to my knowledge as when you join, errors still spam but Scoreboard still work.

[latest.log](https://paste.gg/p/anonymous/3f5924251e014787a6fb7312da0d2360)

**Comment by pronze** [comment]
Fixed in the latest snapshot
