### ISSUE TITLE
2 errors on startup

### ISSUE THREAD

**Issue by larssieboy18** [pronze/SBAHypixelify#65]
Hi there,

I have 2 errors on startup. The first one mentions there is no valid plugin.yml file in the .jar file: https://mcpaste.io/cad8df1fc8b5deff.

The second one consists of this error: https://mcpaste.io/858f2095df2bede5

I am using the latest 0.3 snapshot of screaming bedwars and the latest paper tuinity fork.

**Comment by larssieboy18** [comment]
Also, the plugin causes the server to crash altogether, see the following crash report(s):

https://mcpaste.io/eec39c53d75f77d6 & https://mcpaste.io/22893202e06f167c

**Comment by pronze** [comment]
Probably an issue with tuinity, contact them first. and make sure to send the entire log file

**Comment by larssieboy18** [comment]
I tried again on Paper, same issue: https://bin.bloom.host/misuyamuca
