### ISSUE TITLE
team collision

### ISSUE THREAD

**Issue by dragonwocky** [pronze/SBAHypixelify#7]
would it be possible to prevent player collision/damage within a team? (e.g. https://www.reddit.com/r/Minecraft/comments/70n9ms/player_collision/)

a few of our players keep accidentally pushing each other off bridges lol

**Comment by pronze** [comment]
Sure, try snapshot version 75 from here https://ci.screamingsandals.org/job/SBAHypixelify/

**Comment by dragonwocky** [comment]
@pronze doesn't work.

**Comment by pronze** [comment]
https://ci.screamingsandals.org/job/SBAHypixelify/75/ try snapshot 75 then and let me know

**Comment by dragonwocky** [comment]
sorry for such a late response, haven't been on minecraft in a while! it's working now, thanks :)

**Comment by pronze** [comment]
That's good to hear :)
