### ISSUE TITLE
I don't get wooden sword, my tools and armor after I die

### ISSUE THREAD

**Issue by PythonasG** [pronze/SBAHypixelify#71]
When I die, I respawn with no armor and my tools, sword.

**Comment by TheHolyFire** [comment]
Hey did you add the items to respawn items?
player-respawn-items: true
gived-player-respawn-items: 
- LEATHER_HELMET
- LEATHER_BOOTS
- LEATHER_LEGGINGS
- LEATHER_CHESTPLATE
- WOODEN_SWORD

**Comment by Chumb3x** [comment]
where should I type gived-player-respawn-items:

**Comment by Square661** [comment]
@Chumb3x I have responded to your other issue with the answer. Please check there.
