### ISSUE TITLE
Plugin is not loading

### ISSUE THREAD

**Issue by WaffleCodez** [pronze/SBAHypixelify#75]
When I add the plugin to my plugins folder on my 1.16.4 Spigot server, the plugin does not load and does not create the required configuration files.

**Comment by pronze** [comment]
The server must be running on java 11 for hypixelify to work.

**Comment by musixr** [comment]
> The server must be running on java 11 for hypixelify to work.

I do not understand you  , how do it?

**Comment by Square661** [comment]
@musixr When you setup your server you get the option to choose what java version you are using. What do you use to host your server? If you tell me this then i will be able to tell you how to have your server running java 11.

**Comment by musixr** [comment]
spigot 1.12

**Comment by Square661** [comment]
@musixr If you need help making your server run java 11. Please answer the question i asked above.
'What do you use to host your server?'

**Comment by pronze** [comment]
Closing issue, feel free to reopen it if the issue persists
