### ISSUE TITLE
how to make that when you will die you will have armor and tools help

### ISSUE THREAD

**Issue by Chumb3x** [pronze/SBAHypixelify#79]
how to make that when you will die you will have armor and tools
Help please

**Comment by Square661** [comment]
@Chumb3x 
Make sure your config file looks like this
`game-start-items: true
player-respawn-items: false
gived-game-start-items:
  - wooden_sword
  - leather_helmet
  - leather_boots
  - leather_leggings
  - leather_chestplate
gived-player-respawn-items:
   - wooden_sword
   - leather_helmet
   - leather_boots
   - leather_leggings
   - leather_chestplate`
Make sure both "player-respawn-items" and "gived-game-start-items are set to true and that they both have the above items.

**Comment by Chumb3x** [comment]
Thanks
