### ISSUE TITLE
How to make  java11 ?

### ISSUE THREAD

**Issue by musixr** [pronze/SBAHypixelify#80]
How make java11 ?

**Comment by Square661** [comment]
I responded to this question in your other issue. #75

**Comment by pl77** [comment]
@musixr are you running Minecraft under itzg's docker container?  Then just add `:latest` to the container label: 

https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version

If you're running it on the server itself, you likely need to update your java version directly.  You can find Java 11 downloads here: https://www.oracle.com/ca-en/java/technologies/javase-downloads.html

Or they are usually available through your server package handler, i.e. `apt-get` or similar commands.  I'd strongly suggest answering Square661's question about how you are running your Minecraft server, i.e. are you subscribed to a server provider, running at home under windows 10, using a raspberry pi?   None of us are mind readers and we can't help you update Java until you give more information.

**Comment by pronze** [comment]
Closing issue
