### ISSUE TITLE
Disabling parties also disables the lobby scoreboard

### ISSUE THREAD

**Issue by Jecket22** [pronze/SBAHypixelify#81]
For some odd reason, disabling the party functionality in bwaconfig.yml will also disable the scoreboard in a set lobby, even if set again with `/bwa setlobby` in-game. I'm not sure if I'm using an old version (v1.4.0) but I thought this might be necessary anyways.

**Comment by pronze** [comment]
Upgrade to 1.4.3, or use the latest V2.0-Snapshots (Also make sure to have latest version of bedwars),
https://ci.screamingsandals.org
