### ISSUE TITLE
Keeping armor and gear

### ISSUE THREAD

**Issue by cnsusanto75** [pronze/SBAHypixelify#83]
I use a minehut server with hypixel addon, the actual gameplay works very well except the only thing that doesn't work for me is keeping armor, swords, pickaxes, and axes. Whenever anyone dies, everything is gone. Also, if I place an enderchest will it carry over between games or does it reset?

**Comment by cnsusanto75** [comment]
[44P7chRh.txt](https://github.com/pronze/SBAHypixelify/files/6092905/44P7chRh.txt)
here is my config file

**Comment by pronze** [comment]
Send your latest.log file here via https://www.paste.gg

**Comment by cnsusanto75** [comment]
https://paste.gg/p/anonymous/b32b7a874acc4ded898d00ed87f00125

**Comment by cnsusanto75** [comment]
https://paste.gg/p/anonymous/b32b7a874acc4ded898d00ed87f00125

**Comment by pronze** [comment]
You're using an old version of SBAHypixelify, Please upgrade to 1.4.3

**Comment by cnsusanto75** [comment]
I use this on a minehut server can i still update, and if yes how?

**Comment by pronze** [comment]
Ask minehut
