### ISSUE TITLE
Shop and Upgrade Shop don't working

### ISSUE THREAD

**Issue by DiaxManPl** [pronze/SBAHypixelify#86]
I haven't changed anything in the `shop.yml` file, but it shows me it's invalid.

**Comment by pronze** [comment]
Send your latest.log file here via https://paste.gg

**Comment by DiaxManPl** [comment]
Ok. This may take an hour or so.

**Comment by DiaxManPl** [comment]
Because I'm running my server on free minecraft hosting so if I would to view files I must stay in queue.

**Comment by DiaxManPl** [comment]
https://paste.gg/p/anonymous/56b8626265e2422aa33cb9afb5b164e7

**Comment by DiaxManPl** [comment]
Erm. Anyone can answer?

**Comment by zlataovce** [comment]
the log says it, invalid shop.yml configuration. run your shop.yml through [YAML Checker](https://yamlchecker.com) and fix your syntax.

**Comment by DiaxManPl** [comment]
Ok. Thank you. Fixed.
